# Generated by Django 5.2.8 on 2025-11-06 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='assets_asse_name_e4d2fa_idx'), models.Index(fields=['created_at'], name='assets_asse_created_6d1779_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='assets_loca_name_a0c6a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='assets.asset')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.location')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='assets_asse_asset_i_e49609_idx'), models.Index(fields=['location', 'timestamp'], name='assets_asse_locatio_fd8b7d_idx')],
            },
        ),
    ]
